[build]
  publish = "public"
  command = "echo 'No build process needed for static site'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Environment variables for production
# These should be set in Netlify dashboard:
# OPENAI_API_KEY = your_openai_api_key
# SUPABASE_URL = https://vzmvgyxsscfyflgxcpnq.supabase.co
# SUPABASE_ANON_KEY = your_supabase_anon_key
# SUPABASE_SERVICE_KEY = your_supabase_service_key (for user deletion)

# Headers for security and cache control
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets for longer
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"